name: CI - Hello

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from GitHub Actions"

